Web/Controllers/CouponController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Web.Models;
using Web.Services.IServices;

namespace Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService couponService;

        public CouponController(ICouponService couponService)
        {
            this.couponService = couponService;
        }
        public async Task<IActionResult> CouponIndex()
        {
            ResponseDTO? response = await couponService.GetAllAsync();
            List<CouponDTO> list = new();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CouponDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        public IActionResult CreateCoupon()
        {
            CouponDTO couponDTO = new();
            return View(couponDTO);
        }

        [HttpPost]
        public async Task<IActionResult> CreateCoupon(CouponDTO couponDTO)
        {
            ResponseDTO? response = await couponService.CreateAsync(couponDTO);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Create Successful";
                return RedirectToAction("CouponIndex");
            }
            TempData["error"] = response.Message;
            return View(couponDTO);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteCoupon(string Code)
        {
            ResponseDTO? response = await couponService.GetByCode(Code);
            if (ModelState.IsValid)
            {
                if (response != null && response.IsSuccess)
                {
                    CouponDTO? coupon = JsonConvert.DeserializeObject<CouponDTO>(Convert.ToString(response.Result));
                    return View(coupon);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCoupon(CouponDTO couponDTO)
        {

            if (ModelState.IsValid)
            {
                ResponseDTO? response = await couponService.DeleteAsync(couponDTO.Id);
                if (response is not null && response.IsSuccess)
                {
                    TempData["success"] = "Delete Successfully";
                    return RedirectToAction("CouponIndex");
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return View(couponDTO);
        }

        [HttpGet]
        public async Task<IActionResult> EditCoupon(string Code)
        {
            ResponseDTO? response = await couponService.GetByCode(Code);
            if (ModelState.IsValid)
            {
                if (response != null && response.IsSuccess)
                {
                    CouponDTO? coupon = JsonConvert.DeserializeObject<CouponDTO>(Convert.ToString(response.Result));
                    return View(coupon);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditCoupon(CouponDTO couponDTO)
        {
            if (ModelState.IsValid)
            {
                ResponseDTO? response = await couponService.UpdateAsync(couponDTO);
                if (response is not null && response.IsSuccess)
                {
                    TempData["success"] = "Update Successfully";
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return View(couponDTO);
        }
    }
}

Web/Views/Coupon/CouponIndex.cshtml
@using System.Globalization;
@model IEnumerable<CouponDTO>
@{
    ViewData["Title"] = "Index";
}

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white">Coupon List</h1>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a class="btn btn-outline-primary" asp-controller="Coupon" asp-action="CreateCoupon">
                    <i class="bi bi-plus-square"></i>
                    Create New Coupon
                </a>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Coupon Code
                    </th>
                    <th>
                        Discount Amount
                    </th>
                    <th>
                        Minimum Amount
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Code
                        </td>
                        <td>
                            @string.Format(new CultureInfo("vi-VN"), "{0:c}", item.Discount)
                        </td>
                        <td>
                            @string.Format(new CultureInfo("vi-VN"), "{0:c}", item.MinAmount)
                        </td>
                        <td>
                            <a asp-controller="Coupon" asp-action="EditCoupon" asp-route-Code="@item.Code" class="btn btn-danger">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                            <a asp-controller="Coupon" asp-action="DeleteCoupon" asp-route-Code="@item.Code" class="btn btn-danger">
                                <i class="bi bi-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Web/Views/Coupon/CreateCoupon.cshtml
@model CouponDTO

@{
    ViewData["Title"] = "CreateCoupon";
}

<form asp-action="CreateCoupon">
    <br />
    <div class="container border pb-3">
        <h1 class="text-white text-center">Create Coupon</h1>
        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size: 20px;">Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size: 20px;">Discount Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size: 20px;">Min Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="MinAmount" class="form-control" />
                <span asp-validation-for="MinAmount" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a class="btn-primary btn form-control" asp-action="CouponIndex">Back to List</a>
            </div>
            <div class="col-5 ">
                <input type="submit" value="Create" class="btn btn-primary form-control" />
            </div>
        </div>
    </div>

</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Web/Views/Coupon/DeleteCoupon.cshtml
@using System.Globalization;
@model CouponDTO
@{
    ViewData["Title"] = "DeleteCoupon";
}



<form asp-action="DeleteCoupon">
    <br />
    <div class="container border pb-3">
        <h1 class="text-white text-center">Create Coupon</h1>
        <input asp-for="Id" hidden />
        <input asp-for="Code" hidden />
        <input asp-for="Discount" hidden />
        <input asp-for="MinAmount" hidden />
        <hr />
        <div class="row">
            <div class="col-3">
                <label class="control-label pt-2 text-white" style="font-size: 20px;">Coupon Code</label>
            </div>
            <div class="col-9 pb-3">
                <label class="control-label pt-2" style="font-size: 20px;">@string.Format(new CultureInfo("vi-VN"), "{0:c}", Model.Code)</label>
            </div>
            <div class="col-3">
                <label class="control-label pt-2 text-white" style="font-size: 20px;">Discount Amount</label>
            </div>
            <div class="col-9 pb-3">
                <label class="control-label pt-2" style="font-size: 20px;">@string.Format(new CultureInfo("vi-VN"), "{0:c}", Model.Discount)</label>
            </div>
            <div class="col-3">
                <label class="control-label pt-2 text-white" style="font-size: 20px;">Min Amount</label>
            </div>
            <div class="col-9 pb-3">
                <label class="control-label pt-2" style="font-size: 20px;">@string.Format(new CultureInfo("vi-VN"), "{0:c}", Model.MinAmount)</label>
            </div>
            <div class="col-5 offset-2">
                <a class="btn-primary btn form-control" asp-action="CouponIndex">Back to List</a>
            </div>
            <div class="col-5 ">
                <input type="submit" value="Delete" class="btn btn-primary form-control" />
            </div>
        </div>
    </div>

</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Web/Views/Coupon/EditCoupon.cshtml
@using System.Globalization;
@model CouponDTO
@{
    ViewData["Title"] = "DeleteCoupon";
}



<form asp-action="EditCoupon">
    <br />
    <div class="container border pb-3">
        <h1 class="text-white text-center">Create Coupon</h1>
        <input asp-for="Id" hidden />

        <hr />
        <div class="row">
            <div class="col-3">
                <label class="control-label pt-2 text-white" style="font-size: 20px;">Coupon Code</label>
            </div>
            <div class="col-9 pb-3">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger" />
            </div>
            <div class="col-3">
                <label class="control-label pt-2 text-white" style="font-size: 20px;">Discount Amount</label>
            </div>
            <div class="col-9 pb-3">
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger" />
            </div>
            <div class="col-3">
                <label class="control-label pt-2 text-white" style="font-size: 20px;">Min Amount</label>
            </div>
            <div class="col-9 pb-3">
                <input asp-for="MinAmount" class="form-control" />
                <span asp-validation-for="MinAmount" class="text-danger" />
            </div>
            <div class="col-5 offset-2">
                <a class="btn-primary btn form-control" asp-action="CouponIndex">Back to List</a>
            </div>
            <div class="col-5 ">
                <input type="submit" value="Update" class="btn btn-primary form-control" />
            </div>
        </div>
    </div>

</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}